spring:
  profiles:
#    active: usage_message
    active: work-queues,receiver
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456

logging:
  level:
    org: info

tutorial:
  client:
    duration: 10000
